# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicSongsAlamofire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicSongsAlamofire

  target 'MusicSongsAlamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicSongsAlamofireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

	source 'https://github.com/CocoaPods/Specs.git'
	platform :ios, '12.0'
	pod 'Alamofire'
	

end
